export const ADD_ITEMS_TO_CART = "ADD_ITEMS_TO_CART";
export const GET_CART_ITEMS_COUNT = "GET_CART_ITEMS_COUNT";
export const DECREASE_ITEM_QUANTITTY="DECREASE_ITEM_QUANTITTY";
export const REMOVE_ITEMS_FROM_CART = "REMOVE_ITEMS_FROM_CART";